### ISSUE TITLE
Blog Overview Page - Side Bar Edits

### ISSUE THREAD

**Issue by PolitoTech** [PolitoTech/FCI-WP#18]
1. Browse Blog Topics --> only want these post types:

From the Sales Team
Marketing Update
Marketing Best Practices
Salesforce Best Practices
Sales and Marketing Alignment

Also here we need to actually have these categories linked to the post types because when you click on them they just show all the blogs instead of the specific ones for that category.  Want to show a page with all the posts that are tagged under these types.

---
1. Our Bloggers --> remove these:
   Pratibha
   Admin
   Susan Habernigg
   Jennifer Iguarta
   Politotech

Also when you click on the blogger picture/avatar it either needs to show a page with all the blogs written by that person or to a page with their bio

---
1. Popular Posts --> needs to pull from actual blog posts, not all the pages

---
1. I hyperlinked the buttons to the right assets so that is taken care of.

**Comment by kossa** [comment]
- For the First issue(Browse Blog Topics) Fixed 
- Our Bloggers : Need new page => new Design
- Popular Posts : Need to develop a new plugin, I never did it
- I hyperlinked the buttons ...etc I did not understand
