### ISSUE TITLE
Products Page - Mobile - Text not wrapping correctly next to quote logo

### ISSUE THREAD

**Issue by PolitoTech** [PolitoTech/FCI-WP#2]
![2015-07-07_11-27-18](https://cloud.githubusercontent.com/assets/4174069/8549982/b5fc5d26-249b-11e5-8573-4c88740220ac.png)

**Comment by PolitoTech** [comment]
This is also happening on all other page templates.

**Comment by kossa** [comment]
http://i.imgur.com/aaVFKnX.png
