### ISSUE TITLE
Careers - Post Type Functionality Not working

### ISSUE THREAD

**Issue by PolitoTech** [PolitoTech/FCI-WP#22]
About us-careers: In careers section none of the links to the job posts work.  Need to be able to edit this page and create posts that get linked to the actual job listings. The categories you made for these post types are not setup on page template

**Comment by PolitoTech** [comment]
![2015-07-10_12-31-32](https://cloud.githubusercontent.com/assets/4174069/8623489/b5e7fece-26ff-11e5-8275-f5ab213a5bb6.png)

**Comment by kossa** [comment]
Ahh I need the design for careers details ;)

**Comment by PolitoTech** [comment]
Need to be able to add careers as blog posts. They can only be seen in Careers Page. They would like the ability to add locations and posts under each location.
