### ISSUE TITLE
Rotating Quotes - Some have quote mark on second line from quote text 

### ISSUE THREAD

**Issue by PolitoTech** [PolitoTech/FCI-WP#23]
rotating quotes on homepage and pricing page: end block quote mark in the elastic and xactly quotes is on the line below the text.  should be on the same line.

![2015-07-10_12-36-49](https://cloud.githubusercontent.com/assets/4174069/8623614/7b3d8d1a-2700-11e5-8268-33939e580fa6.png)

**Comment by kossa** [comment]
Bcz It's the end of the line, you should change the Quote :)
